### ISSUE TITLE
Inconsistent property names in documentation

### ISSUE THREAD

**Issue by jpmckinney** [opensupporter/osdi-docs#158]
`birthdate` is in the table at http://opensupporter.github.io/osdi-docs/people.html but it's `birth_date` in the example JSON. The underscored version is what I would expect, given that all other multi-word properties are underscored. Is this just a typo?

`given_name`, `family_name` and `additional_name` are in the table at http://opensupporter.github.io/osdi-docs/people.html but I see `first_name`, `last_name` and `middle_name` in other parts of the docs. Should those be updated to use `given_name`, etc.?

Which property names are correct? Once I know, I can write a pull request.

**Comment by jpmckinney** [comment]
I still see `first_name` in places like http://opensupporter.github.io/osdi-docs/ but `given_name` in places like http://opensupporter.github.io/osdi-docs/people.html … 🤷‍♂️

**Comment by joshco** [comment]
Good catch.  Reopening this one.
