### ISSUE TITLE
Notes and Attachments

### ISSUE THREAD

**Issue by joshco** [opensupporter/osdi-docs#18]
This issue arose with a request to add a 'notes' attribute to interactions to capture CRM like info.
This can also be useful on all objects.
An alternative is suggested to have attachments collections which could include text notes, files, etc as well as metadata like author, date

**Comment by vinnyrose** [comment]
Being able to attach images would have been extremely useful for a current project I'm working on. As it stands now the only solution we have is to have users provide a URL to an image of themselves.

**Comment by joshco** [comment]
I have an avatar attribute in hero for the volunteer's picture, so I'm in favor of standardizing something.
We could choose to treat avatar as a first class attribute or let it be one of many attachments.
My sense is that due to its commonality and a desire for simplicity in retrieving it that it should be a first class attribute.

Would a URL be sufficient as the value of the attribute?

**Comment by vinnyrose** [comment]
It might be useful to return a map of different sized avatars.
