### ISSUE TITLE
What is HTTP response content type?

### ISSUE THREAD

**Issue by joshco** [opensupporter/osdi-docs#190]

**Comment by j-ro** [comment]
Just a standard header that clients will send and return, used on the examples to show what type of content to expect. In this case, hal+json

**Comment by raysuelzer** [comment]
However, for post / put the standard is to use application/json instead of
hal+json (at least that is how the hal browsers seem to work).



Ray Suelzer
Mobile: (312) 869-2665

**Comment by joshco** [comment]
Proposal is to use application/json for requests and responses.
Approved

**Comment by joshco** [comment]
Needs text added to spec

**Comment by joshco** [comment]
Added
