### ISSUE TITLE
Review Question Answers

### ISSUE THREAD

**Issue by joshco** [opensupporter/osdi-docs#191]
open issues discovered while doc update (ray).
If we are dropping QuestionResponses, then what do answers point to?

**Comment by j-ro** [comment]
Answers point to the question that they originated with, and also the person who answered the question. See here for our implementation:

https://actionnetwork.org/docs/v1/question_answers

**Comment by raysuelzer** [comment]
So if I want to get a persons specific answers to a specific question what
would the endpoint be, or is that not possible in the current spec?

https://actionnetwork.org/api/v1/people/[person_id]/questions/[question_id]


Ray Suelzer
Mobile: (312) 869-2665

**Comment by j-ro** [comment]
The way we think about it, it's more like:

https://actionnetwork.org/api/v1/people/[person_id]/answers/[answer_id]?filter="question eq [question_id]"

So, it's the answers that are joined to people, not questions, and you'd use filters to look through a person's collection of answers.

**Comment by j-ro** [comment]
Sorry, no, you'd go the other way:

https://actionnetwork.org/api/v1/questions/[question_id]/answers/?filter="person eq [person_id]"

If you know what question and person you want, but not the answer, then you'd look at all answers to a question and filter by the person you want.

**Comment by j-ro** [comment]
Also, I'll note that we embed the question with the answer, so if you're looking at all the answers for a person you can see what question they answered as well. Optional, but useful.

**Comment by joshco** [comment]
closed per discussion 1/22/15
