### ISSUE TITLE
Custom question fields for Event signups

### ISSUE THREAD

**Issue by goldnate** [opensupporter/osdi-docs#195]
I have been using SalsaLabs with an AFT local for a few years now. Every so often we will have an event in which we need some kind of information from each supporter that is specific to the event.

For example, we might have a dinner in which attendees need to indicate fish, chicken or vegetarian. We could make these custom fields on the person, but this would tie that information to the person and not their attendance at the event. This is problematic for two reasons: 
1. It can create wasteful sets of custom fields in the Person format that were only created for one event, but stick in the Person data table for all eternity and 
2. if the same person signs up for two events in the same time period that require similar questions (e.g. two fundraisers, both with the same food options), it is tempting to re-use the same custom Person field, which results in a problematic overwrite.

One way of getting around this would be to use the Questions data format and associate the given survey with a particular event (this model could also be extended to other forms of participation: ie actions, donations). With this model, it would be easy to associate the survey back to the event by simply including a (hidden?) field identifying the event key. However, where does the link in the other direction exist? Can there be a field that links the event (or other means of participation) to the survey?

In trying to deal with this issue, I have done some crazy js hacks on my signup pages. Mainly, I have created a hidden textarea custom field that I generally use for custom data and write the results of various other form fields into it in my own format. [I’ve extended the registration on this past event so you can see an example of my ridiculous hacks](https://afl.salsalabs.com/o/4013/c/468/p/salsa/event/common/public/?event_KEY=12013).

Anyway, that’s all I have to ask. Just contact me with any questions.

**Comment by j-ro** [comment]
I think questions and answers is the best way to go for this. We should probably extend our model so that events (and our other action types) can have links to question answers like forms do, to officially support this type of linking.

**Comment by goldnate** [comment]
You would be my (s)heroes.
