### ISSUE TITLE
Implementing osdi on civicrm

### ISSUE THREAD

**Issue by tttp** [opensupporter/osdi-docs#198]
Hi,
We are applying for Google summer of Code again this year, and one of the suggested project is osdi interface. The main focus will be to implement it on civicrm, but some of the tasks (eg. testing) can potentially be used by other projects.

And if one of you is interested to co-mentor and get involved in the project (civi is used by > 9k organisations), please contact me, I'd love to hear you

**Comment by tanderegg** [comment]
That sounds like a great idea.  While I haven't used CiviCRM in quite a while, I'm happy to provide help from the OSDI perspective.

**Comment by joshco** [comment]
@tttp Can shoot me a mail at joshco at gmail dot com ?
We should tee up a conversation with our governance committee

**Comment by joemcl** [comment]
Hey Josh & Xavier, Tim Otten, who works with developer/API/architecture issues in CiviCRM, would be interested in a joining a Hangout about OSDI, as well as a couple key CiviCRM developers. Josh can you join a hangout that I'll put together with these folks?

**Comment by ginkgomzd** [comment]
I'd be interested in the hangout as well.

**Comment by tttp** [comment]
Count me in.

**Comment by joshco** [comment]
I sent you a thread on this in email. Did u see it?

**Comment by joemcl** [comment]
Josh, thanks, sent e-mail to everybody above. Proposing a Hangout ( or we can use lucidmeetings, tokbox, whatever) at 4pm Eastern time on Monday.

**Comment by totten** [comment]
I can do 4pm Eastern on Monday (3/30).

**Comment by joemcl** [comment]
Tim, Monday 3/23 at 4pm Eastern does not work then?

**Comment by joemcl** [comment]
@tanderegg sorry don't have your e-mail, didn't include you on the e-mail chain. So everybody - how about Monday 3/30 at 4PM Eastern then?

**Comment by tanderegg** [comment]
I may be able to hop on for a bit, if not I'll get the outcomes from Josh.
Thanks!

Tim

**Comment by totten** [comment]
I apologize. Monday, 3/23 does work fine for me. I misread the calendar. Either Monday works fine.

**Comment by kreynen** [comment]
I'll participate if I'm available, but I was primarily following up on the
GitHub issue Xavier started after seeing the OSDI session at SXSW.

This is obviously in very capable hands.  If you decide to do the GSoC
route, I may have a CU student who'd be interested in working on this.

- Kevin

**Comment by joemcl** [comment]
Cool, Kevin and Tim Anderegg can you please both shoot Josh an e-mail at joshco at gmail dot com and he'll add you to the calendar invite for Monday 3/23 at 4pm. Thanks. Looking forward to it!

**Comment by tttp** [comment]
So thanks to @joemcl, it seems we'll use one of the GSoC slot for a bright student that will work on OSDI (not official yet, let's keep it between ourselves ;)

@tanderegg (or someone with knowledge about OSDI), would you be interested to join as a co-mentor?

@joshco I'm sending you an email re governance committee

**Comment by tanderegg** [comment]
I'd be happy to help.
