### ISSUE TITLE
petition target attributes

### ISSUE THREAD

**Issue by thinkcontext** [opensupporter/osdi-docs#203]
Currently the petition target object only has one attribute, name.  My use case involves identifying a url associated with a target for a web browser extension that is able to display petitions on the target's website, social media presences, 3rd party websites, etc.

Perhaps just a url attribute would be sufficient but it might be nice to have a foreign identifier object.  Something like:

```
target: {name: "Barack Obama",
        identifiers: { website: "https://www.barackobama.com/",
                            wikipedia: "https://en.wikipedia.org/wiki/Barack_Obama",
                            twitter: "https://twitter.com/barackobama",
                            ...
                          }
        }
```

or

```
target: {name: "Fancy Restaurant",
             identifiers: { website: "http://fancyrestaurant.com",
                                 openstreetmap: "http://www.openstreetmap.org/way/238241022",
                                 yelp: "http://yelp.com/biz/fancy-restaurant",
                                 ...                                
                              }
           }
```

Being able to support different types of foreign identifiers enables mashups using linked data.  On the frontend it allows the use of autocomplete functionality, map selects, etc.

**Comment by j-ro** [comment]
This is pretty interesting, thanks! Can you show us an example of this in action, so I can connect the dots a bit?

**Comment by thinkcontext** [comment]
Sure, here's an example.  A coworker.org petition targeting a restaurant accused of wage theft appearing on that restaurant's Yelp page ![petition](https://pbs.twimg.com/media/CBmhvEDUoAABimZ.png)

To get this to work, I had to write an [application](https://github.com/thinkcontext/tcsem) to ingest petitions and then do semi-manual semantic tagging.  From my perspective this would be much better done in the source CMS.

This example is live in the browser extension, along with over 20 other data sources not just petitions.  If you'd like to see more check out [thinkcontext.org](http://thinkcontext.org).

**Comment by j-ro** [comment]
Thanks! Very interesting. I guess the question for me is, do systems in the OSDI coalition actually maintain this data, so that they could make it available over an OSDI API. 

We don't -- when someone enters a petition target they're just typing text into a box, it's not like they have a list to choose from or they bring meta data along with them. Even for our advocacy tools (see the targets on the advocacy proposal that just got merged this afternoon) we don't have things like twitter accounts for members of congress, though there are APIs that have these things, some of which we use.

Which is not to say we shouldn't add these things necessarily, but would be good to hear from other OSDI members to see what they think and if they maintain this data.

**Comment by thinkcontext** [comment]
Hope you consider it, I think it could provide significant value for integration.

I know Change.org is not an OSDI member but they do [provide autocomplete](http://making.change.org/post/69092404340/introducing-autocomplete-to-improve-petition) for end users creating petitions.  Unfortunately, their api doesn't expose any foreign keys.

**Comment by thinkcontext** [comment]
It looks like Salsa has the ability to have petition targets with a variety of attributes.

https://help.salsalabs.com/entries/22555438-target-recipients

**Comment by j-ro** [comment]
Sure, we have similar, we take title, first name, last name, zip code, email address. But that's not really what you're talking about here -- there's no website or twitter account or wikipedia whatever.
