### ISSUE TITLE
Proposal: add the "add_tags" and "add_lists" fields to other helpers

### ISSUE THREAD

**Issue by j-ro** [opensupporter/osdi-docs#207]
...instead of just the person signup helper. Same format, an array of strings, so you'd get something like this:

```
POST https://actionnetwork.org/api/v2/forms/adb951cb-51f9-420e-b7e6-de953195ec86/submissions/

Header:
Content-Type: application/json
OSDI-API-Token: your_api_key_here

{
  "identifiers": [
    "free_forms:2"
  ],
  "person" : {
    "family_name" : "Smith",
    "given_name" : "John",
    "postal_addresses" : [ { "postal_code" : "20009" }],
    "email_addresses" : [ { "address" : "jsmith@mail.com" }]
  },
  "add_tags": [
    "volunteer",
    "member"
  ]
} 
```

Simple enough -- what do folks think?

**Comment by joshco** [comment]
+1
@shaisachs I was also wondering if we should add an add_answer function to simplify question answers (for those scenarios not using custom fields)

````
"add_answers": [
   "question_name": {
      "value": "answer_value",
      "responses" : [ "r1", "r2", "r2"]
   }
]
````

**Comment by j-ro** [comment]
I don't mind it, he should propose it! We aren't implementing answers, so really, whatever! :)

**Comment by shaisachs** [comment]
Speaking to the original proposal - I guess that's fine but we should specify which actual helpers we're talking about and what the semantics are?  I'm not sure add_lists makes sense in the canvass helper, for example. (Or maybe I'm not thinking broadly enough, who knows.)

I think add_answers makes sense in the context of person signup helper but will have to circle back to that.  I'll make an issue for it to at least bookmark the idea.

**Comment by j-ro** [comment]
In my mind, they would all make sense everywhere, at least in certain scenarios. 

Like, add lists, some systems will treat this like a subscription list. So you would want to add to certain subscriptions in the context of any of these helpers. 

But whether you implement it on a certain endpoint yourself is server behavior. For us, lists represent being targeted by an email or report. So add list doesn't make sense and we aren't implementing it. For you, adding answers on person signup might not make sense, but it could for others. 

Still, seems useful to have these specced everywhere for consistency, even if you don't implement them all.

**Comment by shaisachs** [comment]
Ok, I see that.  We may not implement those features but if you want to, no reason to block it.

**Comment by joshco** [comment]
Next steps: Jason to produce pull request to review next week
