### ISSUE TITLE
Non-authenticated POST

### ISSUE THREAD

**Issue by j-ro** [opensupporter/osdi-docs#210]
This one may not necessarily need a spec change, but perhaps...

The idea is to allow a POST format that is ok for frontend javascript applications. So, you could make a signup form and POST it in over javascript/AJAX. This means basically no authentication, since you wouldn't want to give away that key. 

My idea would be to allow the normal POST format (helpers included) against a valid endpoint but if no API key was used (and if the server supported it), then the response from the server would simply be the status code (200 for success, 4-500 errors for not). That way, data can come in but no data leaks back out in the response.

**Comment by joshco** [comment]
jason to generate pull request
