### ISSUE TITLE
Autoresponse bool for helpters

### ISSUE THREAD

**Issue by j-ro** [opensupporter/osdi-docs#211]
Some servers, like ours, send autoresponse emails when someone takes an action (say, if you sign a petition, you get an autoresponse email back thanking you for signing).

Right now, if you "sign" over the API we don't send that autoresponse. The idea here is to add a bool for helpers that allows you to indicate to the server that it should indeed be sent. So something like:

```
POST /api/v1/petitions/1234/signatures

{
    "person": {
        "given_name": "John",
        "family_name": "Smith,
        "email_addresses": {
            "address": "jsmith@mail.com",
        }
    },
    "add_tags": [
        "signer"
    ],
    "autoresponse": "true"
}

**Comment by joshco** [comment]
1) broaden the syntax beyond boolean
2) investigate modeling discovery of trigger actions on a petition et al

**Comment by j-ro** [comment]
So, for 1, what would this be exactly? We do have some kind of autoresponse stuff modeled on event:

https://github.com/opensupporter/osdi-docs/blob/gh-pages/events.md

```
"reminders": [
                    {
                        "method": "email",
                        "minutes": 1440
                    },
                    {
                        "method": "sms",
                        "minutes": 60
                    }
                ]
```

So maybe that works? It could be an array (if having more than one is a use case? not sure it is..._ and a method (minutes here doesn't make a ton of sense). One of "sms" or "email"?

For 2, I could see adding a similar thing to the parent action resource. So, say, a form could have a `autoresponse` bool (or array/hash, if we take the approach above) that describes whether it would send this thing by default. Then on helpers (and only on helpers, these are like `add_tags` and `add_lists`, only helper fields), you could pass `send_autoresponse` as a true/false, or maybe in the same array/hash style. Whether that passing actually overrode the form's default value would be server behavior, I think. In our case:

**if the autoresponse was on the form:** 

* and you passed false, we would not send it
* and you passed nothing, we would not send it
* and you passed true, we would send it

**if the autoresponse was not the form:** 

* and you passed false, we would not send it
* and you passed nothing, we would not send it
* and you passed true, we would not send it

So our default is towards not sending it, unless you've set it up (it's on the form) and you specifically ask us to. But other servers could handle it differently if they wanted to.

**Comment by joshco** [comment]
I would generalize this more as "triggers" (which will also converge with webhooks)

Any resource can have associated triggers/webhooks.  The name/identifier of them is customer specific, though there is a label for  "default" and "all" triggers.  Examples of triggers could be emails, sms, web POST hook, or a composite.  
When referencing triggers in a helper, the client can specify as much or as little as the customer configured allows.

We should discuss if the default API behavior should be no triggers or if default triggers happen.

## Abstract
````
triggers: {
 trigger_name: {
        enabled: true,
       params {
           my_trigger_param: "my trigger param value"
}
````

## Example: Disable all triggers
````
triggers: {
 all: { enabled: false }
}
````

## Example: Enable email response
````
triggers: {
  "email_thank_you" : {
       enabled: true,
      params: {
        "seconds" : 1440
     }
 }
}
````

## Example: Enable a specific trigger
````
triggers: {
 "joshco_webhook" : {
        enabled: true,
        params: {
           "post_url": "http://joshco/foo"
       }
}
````

**Comment by j-ro** [comment]
I'm not sure any of our coalition implements these types of things over the API, so they may be unlikely to be used beyond the simple email autoresponse. We might even be the only ones considering autoresponse options over the API even, since I'm pretty sure each system right now just sends or doesn't according to its implementation when they receive a petition signature or something. Like, I'm pretty sure Salsa will send whatever its supposed to just like a normal petition signature. We currently don't send anything.

I guess we should survey folks, but if that's the case, I'd argue this is overbuilt for that use case.

**Comment by joshco** [comment]
Current proposal
 ````
triggers: {
 autoresponse: { enabled: true }
}
````
Jason to update review next week

**Comment by robertsonsamuel** [comment]
```json
  "triggers":{
      "autoresponse":{
        "enabled":true,
        "email_autoresponse":{
          "params":{
            "email_id":"087453"
          }
        }
      }
    } 
```

```json
  "triggers":{
      "autoresponse":{
        "enabled":true,
        "sms_autoresponse":{
          "params":{
            "sms_id":"087453"
          }
        }
      }
    } 
```
If I should move this to a new issue let me know, wanted to propose a method for params as we did above. Following the signup api I think a params object could be added to the auto response? That way the signup helper can in turn figure out what to send based on these.

**Comment by j-ro** [comment]
Yeah, new issue please!
