### ISSUE TITLE
How do we represent electronic meetings in osdi events?

### ISSUE THREAD

**Issue by joshco** [opensupporter/osdi-docs#232]

**Comment by j-ro** [comment]
Events without locations?

**Comment by joshco** [comment]
Where would we put the join.me or lucid meeting connection information, eg dial-in, URLs etc

**Comment by j-ro** [comment]
we wouldn't -- I mean, in my system, you'd put that in the event description or instructions. But since there are so many ways to do webinars, not sure a purpose-built field is warrented.
