### ISSUE TITLE
implementing osdi on salesforce.org nonprofit starter pack

### ISSUE THREAD

**Issue by cdcarter** [opensupporter/osdi-docs#236]
Hey folks,

I'm starting to look at the feasibility of implementing (a relevant subset of) OSDI for the Salesforce.org Nonprofit Starter Pack. If anyone is interested, give me a shout.

**Comment by j-ro** [comment]
great! I don't really think I can help, but I support it.

**Comment by cdcarter** [comment]
+1. I'm solving a few issues with getting useful HAL output serialized, but then I'll be able to jump into the actual "sd" part of "osdi"!

**Comment by j-ro** [comment]
Cool -- note on HAL, if you want to, you can probably ignore it. Most OSDI implementations can be treated like standard JSON/REST. But HAL helps you to figure out the REST part, so useful certainly.

**Comment by j-ro** [comment]
Also, just from my experience with Salesforce, I'd encourage an implementation that's as "vanilla" as possible, so not using nonprofit starter pack as much as possible and just using standard objects, since not everyone uses that, so it would be a more general solution. But up to you, really.
