### ISSUE TITLE
Additional options for Attendance status enum: noshow, cancelled

### ISSUE THREAD

**Issue by mpaquette1** [opensupporter/osdi-docs#237]
In ```attendances.md```, the current status options are "declined", "tentative", "accepted", or "needs action".  I propose adding options to cover more use cases.

My company's clients like to label no-shows explicitly in attendance records.  The thinking is that if someone confirms their attendance but then fails to show up, it should not be counted as either a "declined" or an "accepted" -- it's something different, and worse.  Our clients want to attach a stigma to being a no-show, as it reflects on the trustworthiness of the volunteer or erstwhile attendee.

Our system also offers a status option of "cancelled" (the equivalent of "accepted" followed in time by "declined) to show that, while the person didn't attend as originally promised, at least let us know they weren't coming.  Thus we know they *were* interested in the event, and should be invited to future events..

**Comment by j-ro** [comment]
I think the separated attended field covers the first use case -- status might be accepted but attended false.

For the second, sure, I could see adding a cancelled status.

**Comment by mpaquette1** [comment]
Right you are, I neglected the "attended" field which serves the same purpose, albeit in a less-judgmental-sounding and slightly more complicated way.   

A status of "cancelled" shows the organizer that that seat is available for someone else on a waiting list, or lets the organizer know not to set up as many chairs.

**Comment by j-ro** [comment]
Wanna code up a pull request adding in that cancelled status?

**Comment by mpaquette1** [comment]
Sure, but apparently I don't have permission to create a branch or a pull
request.  I can send the text change if you like.


*Mark Paquette*
Co-founder & CTO
thedatabank, gbc. (general benefit corporation
<https://en.wikipedia.org/wiki/Benefit_corporation>)
612-455-3502
mark@thedatabank.com

**Comment by j-ro** [comment]
@joshco, can we fix that?

**Comment by joshco** [comment]
Mark,
The usual process is to fork the repository to your own account.  Then push
to that repo, then make the pull request.
Jason has bad habits :)

On Fri, Jan 15, 2016 at 3:19 PM, Jason Rosenbaum <notifications@github.com>
wrote:

> @joshco <https://github.com/joshco>, can we fix that?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/opensupporter/osdi-docs/issues/237#issuecomment-172079960>
> .
>



-- 

*Josh Co*hen  joshco@gmail.com | @joshco | LinkedIn
<http://linkedin.com/in/joshrcohen/> | GitHub <https://github.com/joshco>
  | OSDI opensupporter.org <http://opensupporter.org/>

Looking for a contract developer to work on APIs, integrations, servers,
WordPress?  Hire me!
"If [OSDI <http://opensupporter.org/>] succeeds, it could usher in the next
chapter in political technology." - Washington Post <http://wapo.st/1hYXX7O>

**Comment by joshco** [comment]
The reason is that early on we had some accidents where people mistakenly pushed commits into master that hadn't been approved by the committee.  Those are a pain to undo.
