### ISSUE TITLE
Make empty JSON object/error message the response for unauthenticated POST

### ISSUE THREAD

**Issue by j-ro** [opensupporter/osdi-docs#239]
Right now, the response to an unauthenticated POST in the spec is simply a status code (say, 200 or 404 or something). There are two issues with this.

First, it's not a valid JSON response, so it will often break javascript/AJAX (and other language) implementations, as they're often expecting a JSON response.

Second, we can include error messages in the spec, since they don't often leak important data, with a note to implementers about making sure they don't.

So, my proposal would be ok success to return an empty JSON object in the message body, along with the 200 header:

```
{}
```

And for errors, to allow error messages to be included, so again we get a valid JSON response.

**Comment by joshco** [comment]
it could also return an OSDI error/status stanza
> http://opensupporter.github.io/osdi-docs/errors.html
NOTE TO US: We never quite nailed this down; it is currently in our experimental section.

**Comment by j-ro** [comment]
Well yeah, on error it would, it would return a normal error, which is that.

On success, though, empty JSON is the right thing I think, since normal behavior is the actual object, which you don't want to return in the unauthenticated case.
