### ISSUE TITLE
Safeguarding PSH in anon scenario

### ISSUE THREAD

**Issue by joshco** [opensupporter/osdi-docs#240]
When doing anonymous OSDI helpers, person signup helper is not safeguarded by an ID or GUID and it is a known URL.  Compare to others:

```
api/v1/fundraising/987123987123987123/record_donation_helper
api/v1/person_signup_helper
```

We could also have a separate parameterized Person Signup Helper for anonymous use.  This can be server behavior.  Might also just be an informational note in spec or we can just do nothing.

**Comment by j-ro** [comment]
I think this is server behavior, but worth noting in the spec so implementers can be aware of the ramifications of the various choices.
