### ISSUE TITLE
Adding profiles.profilepicture field to profiles table

### ISSUE THREAD

**Issue by joemcl** [opensupporter/osdi-docs#242]
Attentive.ly and other sources pull profile pics from Facebook, Twitter, etc. We should support syncing of profile pics if an  implementer wants to include that.

**Comment by j-ro** [comment]
While I see the use case, I also see this as fairly complex, since there can be lots of pictures from various sources and sometimes there are rights or privacy settings attached to each.

**Comment by joemcl** [comment]
@j-ro right but our profiles table field set specifies the profile to be used. Also not sure but presume Attentive.ly can only pull pics and other info from Facebook, Twitter pages that are public anyway? I could be wrong.

**Comment by j-ro** [comment]
Well, there are rights to those. For example, last time I looked, and it may have changed, you couldn't send around a Facebook profile pic, you could pull it if your app has a facebook API key, but it's not your picture, it's not really public.

**Comment by joemcl** [comment]
Hmm. Ok. Will check it out.

**Comment by joemcl** [comment]
"What information is public?
Information you share that is always public: Some of the information you give us when you fill out your profile is public, such as your age range, language and country. We also use a part of your profile, called your Public Profile, to help connect you with friends and family. Your Public Profile includes your name, gender, username and user ID (account number), profile picture, cover photo and networks. This info is also public."

https://www.facebook.com/help/203805466323736

**Comment by joemcl** [comment]
"Remember that public information can:
Be associated with you, even off Facebook
Show up when someone does a search on Facebook or on another search engine
Be accessible to Facebook-integrated games, applications and websites you and your friends use
Be accessible to anyone who uses our APIs, such as our Graph API"
https://www.facebook.com/help/203805466323736

**Comment by j-ro** [comment]
That's not exactly where to look. Rather, you're going to want to look at the Facebook API and the terms of service around there. The question is mostly can I, as a Facebook App developer, take the Facebook avatar image and use it for any purpose other than in my app, such as transferring it to another system over OSDI.

**Comment by joemcl** [comment]
Ok will plow through this later - https://developers.facebook.com/policy/#data

**Comment by j-ro** [comment]
yep, that's a good place to start I think, cool
