### ISSUE TITLE
preferred pronouns

### ISSUE THREAD

**Issue by joshco** [opensupporter/osdi-docs#266]
OSDI should have preferred pronouns like He Him Hers

**Comment by joshco** [comment]
The OSDI committee is seeking community input for representing gender pronouns in the progressive common data specification.

The current proposal is that a gender_pronouns attribute will be added to an OSDI Person. This attribute will be a text field that is expected to have either one of a set of known values to achieve consistency, but also allow a free-text values for expressiveness beyond that.

Currently known values:
She/Her/Hers
He/Him/His
They/Them/Theirs

We are looking for suggestions for additional known values to be incorporated into the specification.

**Comment by joshco** [comment]
Reference materials
http://www.transequality.org/issues/resources/national-transgender-discrimination-survey-full-report
http://www.transequality.org/sites/default/files/docs/usts/USTS%20Full%20Report%20-%20FINAL%201.6.17.pdf

**Comment by sonyabea** [comment]
Annoyingly, the transequality report says about pronouns: "4% indicated that they used pronouns other than those provided  in the answer choices." But they don't say which ones. Maybe it's worth reaching out and asking if they're willing to share all free-form responses they received?

**Comment by sonyabea** [comment]
closed by committee 9/19/2018
