### ISSUE TITLE
OSDI should model chapters/parent architecture

### ISSUE THREAD

**Issue by joshco** [opensupporter/osdi-docs#270]

**Comment by j-ro** [comment]
We do this with separate API keys for each chapter, and are unlikely to change for a host of reasons we can talk about in tech :)

**Comment by joshco** [comment]
I had an interesting convo at organizing2.0 and made me wonder if there are common aspects customers want.  Eg, the set of people is shared abut filtered across chapters, but what about events, petitions etc.  So if you are looking at the people list from the parent, are the associations with petitions or events not visible outside the chapter?

**Comment by j-ro** [comment]
Actions in our system are owned by a group, and relations to those actions are also owned by the group, so the api will report only the results of the group, not parents or children.
