### ISSUE TITLE
Make osdi-docs usable for curies

### ISSUE THREAD

**Issue by hypeJunction** [opensupporter/osdi-docs#275]
It would make life a lot easier, if we could use these docs for templated curies. Currently, some of the entires are missing, e.g. `osdi:modified_by` or `osdi:creator`. Also, singulars should map to collection names: `osdi:event` should map to `events.html`

**Comment by j-ro** [comment]
Seems like this would just be some URL mapping, right? Useful.

**Comment by hypeJunction** [comment]
Maybe it would be easier to add missing pages? Some of those relationships apply to various item types.

**Comment by j-ro** [comment]
Fields themselves should not be curied, but everything else already exists. osdi:creator is just a person object, so it should be instanced to the person spec.

**Comment by joshco** [comment]
Consensus is that we can create stub pages for these exceptional cases that say eg "osdi:creator is just a person" and have a link to a person
@hypeJunction Would you be willing to make a pull request with these updates?

**Comment by hypeJunction** [comment]
I have only a few days before my holiday, but can do it afterwards.

**Comment by sonyabea** [comment]
closed by committee 9/19/2018. Can be reopened with proposed solution.
