### ISSUE TITLE
Allow filter option for searching for people by email

### ISSUE THREAD

**Issue by jkriss** [opensupporter/osdi-docs#278]
Looking up a person by email is a pretty common operation, and since `email_addresses` is a collection, not a direct property, searching by email can't be accomplished with the current filters, if I'm reading the spec correctly.

@joshco mentioned to me that Action Network supports filtering the people collection by the `email_address` term, as documented [here](https://actionnetwork.org/docs/v2/).

Perhaps OSDI should make that part of the official spec.

**Comment by j-ro** [comment]
I think some work on more detail for odata is a great idea. Probably will want to join committee calls but right now it's a bit of a blank slate.

**Comment by joshco** [comment]
Consensus: adopt action network approach for email and expand on others.  basis: https://actionnetwork.org/docs/v2/  (SEARCHING AND FILTERING (ODATA))

**Comment by sonyabea** [comment]
closed by committee 9/19/2018. can be reopened with proposed solution.
