### ISSUE TITLE
Allow filter option for searching people by tag

### ISSUE THREAD

**Issue by jkriss** [opensupporter/osdi-docs#279]
Similar to #278, it would useful to filter the people collection directly by the presence of a given tag. We could add `tag` as a filterable field, where the corresponding filter value would be the id of the tag.

One could imagine doing something similar with `tag_name` for a friendlier query against the name of the tag, rather than the id.

**Comment by j-ro** [comment]
I don't understand this. Isn't /tags/taggings exactly this?

**Comment by jkriss** [comment]
Maybe I'm misreading the docs. Can I do something like `GET /api/v1/people?filter=tag_name eq 'supporter'`?

**Comment by j-ro** [comment]
No, it's a different resource. But /tags/taggings gets you links to all the people who have a tag so not exactly sure why the query is important.

**Comment by jkriss** [comment]
Got it, thanks!
