### ISSUE TITLE
Allow batch query by email address

### ISSUE THREAD

**Issue by jkriss** [opensupporter/osdi-docs#280]
For cross-system sync cases, we often want to see if records exist for a set of email addresses.

If #278 is implemented, perhaps this is as simple as using an OR query in the filter. (Relatedly, is there a maximum number of items for an OR query?)

**Comment by j-ro** [comment]
I think it's unlikely we'd implement batching due to server resources but can see what others think.

**Comment by jkriss** [comment]
If somebody needs to look up a lot of people, I'd think a single batch request would be less load than a series of individual lookups. That said, individual request time could get out of hand, and keeping them as individual requests gives more granularity for rate limiting.

**Comment by j-ro** [comment]
Exactly. Big requests are much worse than a lot of smaller ones for us.

**Comment by jkriss** [comment]
👍🏻
