### ISSUE TITLE
Use OData-compatible path references

### ISSUE THREAD

**Issue by jkriss** [opensupporter/osdi-docs#281]
The [example in the docs](https://opensupporter.github.io/osdi-docs/#filtering-collections), `GET /api/v1/people?filter=gender eq 'Male' and address.postal_code eq '10011'` implies that fields on an object can be referenced using `object.fieldname`. However, OData uses `/`, as in [this example](http://www.odata.org/getting-started/basic-tutorial/#filter).

I've confirmed this using several OData filter parsing libraries, which choke on the `.` delimiter.

Is there a reason OSDI deviates from the OData standard in this case? Do any OSDI-compliant systems actually implement filters for child properties?

**Comment by joshco** [comment]
http://docs.oasis-open.org/odata/odata/v4.0/errata03/os/complete/part2-url-conventions/odata-v4.0-errata03-os-part2-url-conventions-complete.html#_Toc453752356

**Comment by joshco** [comment]
Jesse to make proposal for property filtering to use '/' as consistent with OData

**Comment by jkriss** [comment]
@joshco Would you mind assigning this to me so I can track it? Same for #278 and #284...

**Comment by jkriss** [comment]
@joshco Cool, just put in a separate PR for that one: https://github.com/opensupporter/osdi-docs/pull/287

**Comment by joshco** [comment]
@jkriss sweet

**Comment by sonyabea** [comment]
closed by committee 9/19/2018
