### ISSUE TITLE
Reference implementations?

### ISSUE THREAD

**Issue by jkriss** [opensupporter/osdi-docs#282]
It would be really helpful to have reference implementations of OSDI-compatible servers and clients. That would allow developers to run local servers (with reasonable dependencies and no vendor-specific customizations) and to test OSDI-compatible services with known compatible clients.

**Comment by j-ro** [comment]
Useful, though a big ask for a volunteer effort perhaps :)

This is a project that was started as something similar, not much there, but perhaps a jumping off point of an idea: https://github.com/opensupporter/osdi_validator

**Comment by jkriss** [comment]
If I can get a Swagger spec together, this might make it easy to get a basic (compliant) server together: https://github.com/attn/swagger-express-storage-middleware

And clients can be generated from Swagger specs, as well.

I'll play around with it a bit and report back.

**Comment by joshco** [comment]
We have an example rails app which is more a learning tool for how to implement than a compliance test. 
It was written based on an older version of the spec.  I can give you access to the repo.

**Comment by joshco** [comment]
dependent on machine readable spec, closed until that happens
