### ISSUE TITLE
Machine readable spec

### ISSUE THREAD

**Issue by jkriss** [opensupporter/osdi-docs#284]
As first discussed in #283, it would be helpful to have a machine readable version of the spec for client generation and other uses.

Maybe [Swagger](http://swagger.io/) would be a good choice for this. It's got broad support, as well as mature tooling for generating documentation and clients in various languages.

Incidentally, there's a [Swagger -> GraphQL wrapper](https://github.com/yarax/swagger-to-graphql) (relevant to #283) as well as tools for [generating server stubs](https://github.com/swagger-api/swagger-codegen/wiki/Server-stub-generator-HOWTO) (potentially relevant to #282).

**Comment by j-ro** [comment]
Seems like a useful project! Probably a separate repo or something...

**Comment by joshco** [comment]
Jesse will continue to research and update the group

**Comment by sonyabea** [comment]
closed by committee 9/19/2018. Can be reopened if fix exists.
