### ISSUE TITLE
We do not have a "general concepts document" with "more information about identifiers"

### ISSUE THREAD

**Issue by joemcl** [opensupporter/osdi-docs#285]
Under Common Fields for Resources, for Name=Identifiers of Type=strings[], the Description is "A unique string array of identifiers in the format [system name]:[id]. See the general concepts document for more information about identifiers." We do not have a "general concepts document" with "more information about identifiers" though there is the Introduction at https://opensupporter.github.io/osdi-docs/ .

**Comment by joemcl** [comment]
Commenting on this issue to test GitHub integration with a Slack channel. Please ignore.

**Comment by joemcl** [comment]
Commenting on this issue to test GitHub integration with a Slack channel. Please ignore.

**Comment by sonyabea** [comment]
closed by committee 9/19/2018. Can be reopened at a future date with proposed fix.
