### ISSUE TITLE
Advocacy Campaign Fields: change "target_list" to "targets"

### ISSUE THREAD

**Issue by bnd5k** [opensupporter/osdi-docs#288]
Advocacy Campaigns currently have a field "target_list", which is an array of targets.

https://opensupporter.github.io/osdi-docs/advocacy_campaigns.html#advocacy-campaign-fields.

Would it be possible to change the field name  to "targets"?

In other parts of the spec, when there's an array of targets, the field is simply "targets."

In the Messages resource, the "targets" field is an array of targets.
The https://opensupporter.github.io/osdi-docs/messages.html#message-fields

Record Outreaches also has an array of targets that is represented by "targets."
https://opensupporter.github.io/osdi-docs/record_outreach.html#record-outreach-helper-fields

I'm happy to serve up a PR if you're ok with this change.

**Comment by j-ro** [comment]
It's because advocacy campaigns already have a targets field, which is a string that represents a human-readable title of the target, like "U.S. Congress", and that field is already implemented by systems, so making this change would be a breaking change, which we try to avoid.

**Comment by bnd5k** [comment]
10-4
