### ISSUE TITLE
Specify location based searches

### ISSUE THREAD

**Issue by aaghevli** [opensupporter/osdi-docs#289]
Neither ODATA nor OSDI specify proximity searches. In Resistance Calendar we implemented the following API to support that.

```
# If distance_coords are used, we ignore distance_postal_code and distance_city
http://resistance-calendar.herokuapp.com/v1/events?distance_coords=[-98.435508,29.516496]&distance_max=10000

# If distance_postal_code are used, and not distance_coords, then distance_city is ignored
http://resistance-calendar.herokuapp.com/v1/events?distance_postal_code=94110&distance_max=10000

# distance_city is used if neither distance_postal_code nor distance_coords are provided
http://resistance-calendar.herokuapp.com/v1/events?distance_city=Albuquerque&distance_max=10000
```

**Comment by joshco** [comment]
@aaghevli See http://opensupporter.github.io/osdi-docs/#filtering-collections  OSDI does actually define a filter function 'near' .

**Comment by aaghevli** [comment]
Ah thanks! I was not aware of those and can investigate that a bit more. I am happy to close this until I get a better idea of that API.

**Comment by schuyler1d** [comment]
fwiw, we have a second implementation (of resistance calendar's version) here:
https://github.com/MoveOnOrg/eventroller/pull/33

**Comment by schuyler1d** [comment]
Also, I have a slightly different question than @aaghevli -- can 'near' also be anything besides a zip?  how do you do `near()` with a lat/long or city?  Some additional examples in the spec would help

**Comment by j-ro** [comment]
I think right now it probably only means zip, since we don't specify the field name in the near syntax. This is probably a good area for further work too -- a way to do near on other fields, for example.

**Comment by sonyabea** [comment]
closed by committee 9/19/2018
