### ISSUE TITLE
Events should support more than one organizer

### ISSUE THREAD

**Issue by schuyler1d** [opensupporter/osdi-docs#290]
For backwards compatibility, perhaps it should be `osdi:organizers` (plural) which would be `Person[]`.

Alternatively, you could add a `role` to attendances.  The downside of that is that often systems are only interested in the organizers independently of all of the rsvp'ing attendees.

**Comment by j-ro** [comment]
Seems like a good idea, though a breaking change potentially, and there's already a fair amount of actual implementations of events, so that gets tricky.

**Comment by AaronSofaer** [comment]
I strongly support a solution that lets an `event` resource reflect the reality of multiple organizers existing, however that winds up being implemented.

**Comment by joshco** [comment]
perhaps we could leave the current one to mean primary organizer and have an 'assistants' link or something similar

**Comment by sonyabea** [comment]
closed by committee from inactivity on 9/19/2018. Can be reopened at a future time.
