### ISSUE TITLE
Autoresponse Trigger Params

### ISSUE THREAD

**Issue by robertsonsamuel** [opensupporter/osdi-docs#292]
```json
  "triggers":{
      "autoresponse":{
        "enabled":true,
        "email_autoresponse":{
          "params":{
            "email_id":"087453"
          }
        }
      }
    } 
```

```json
  "triggers":{
      "autoresponse":{
        "enabled":true,
        "sms_autoresponse":{
          "params":{
            "sms_id":"087453"
          }
        }
      }
    } 
```
Wanted to propose a method for params as we did above. Following the signup api I think a params object could be added to the auto response? That way the signup helper can in turn figure out what to send based on these.

**Comment by j-ro** [comment]
So the idea here is this goes on the person signup helper, since that helper would need some kind of ID to identify what response message to send, whereas with things like the record signature helper it's understood that the autoresponse is the one attached to that petition?

**Comment by robertsonsamuel** [comment]
Correct. Looking to expand the idea of the signup helper a little vs just the record signature helper. I think as the OSDI model grows the signup helper is one of the best places to start in terms of development. It's one I've adopted first and allowing to expand this with params would help the spec grow one endpoint at a time.

**Comment by j-ro** [comment]
Definitely agree. Not sure on your proposed structure exactly, params seems maybe a bit abstract for my taste, but I love the idea. Are you able to join our weekly calls? Then we can discuss and you can help push this forward to adoption.

**Comment by robertsonsamuel** [comment]
Might have to be abstract a bit depending on the system, but great! Are those calls still on Thursday's 10AM CT?

**Comment by j-ro** [comment]
Yeah, thinking more just "id" as a field might work, be a bit more straightforward. But anyway, yes, Thursdays at 11am ET/10am CT. If you or your organization is already a member, join. If not, sign up and get on! http://opensupporter.org/

**Comment by robertsonsamuel** [comment]
Just signed up! I think we are a part of the community, but not very involved. Looking to change that! Thanks!

**Comment by j-ro** [comment]
Ah, rev msg, yes, I believe you are. You were in the past, looking forward to new engagement!

**Comment by robertsonsamuel** [comment]
Coming back from our call
## Autoresponse Flow


### Person Signup Helper Flow
The person signup helper acts almost like a overall fourm signup in that it:

1. Creates a new record
2. Has a method to match records
3. Has a method to update a record if it does match
4. Has the option to add tags, and a person to a list
5. Has the option to add question responses
6. Has the option to use triggers


The current spec says that a standard response would be an email. This could be expanded.


As the signup helper makes a lot sense for real-time data to be sent between many systems I think adding a params and a system identifer to the triggers object is a good solution. 

This would be system spesific, but I see __three__ main types of responses at least in my space. 

1. Email
2. SMS
3. Phone Call

I'm open to leaving this as a resource but I don't think an autoresponse resource makes sense as that would be very strange for user to think about if they are generating autoresponses. Even if it was handled by the system.

#### What would this look like? An Example:

Start with a form on OSDI System 1 (NGP/VAN)


1. A form is submitted with a mobile phone number, an email and given name + family name
2. NGP/VAN then as integrations with many services so these are setup when a client wants to add an integration. We add OSDI API Tokens for each service to NGP/VAN, then a person signup helper endpoint is called for each system.
3. Data is then sent via the Person Signup Helper, or updated if it's new in realtime
4. Autoresponses are sent if they are configured in NGP/VAN, lets say, email and an sms message.



The signup helper request would then look like

`Person Signup Helper: POST`

```

{
	"person": {
		"given_name": "Steve",
		"family_name": "Hammers",
		"phone_numbers":[
			{
				"number":"1234567890",
				"primary":true,
				"number_type":"Mobile",
				"sms_capable": true		
		  	}
		],
		"email_addresses": [
            {
                "address":"test@example.com",
                "primary": true,
                "address_type": "Personal"
            }
        ],
        "triggers": {
        	"sms_response":"123456789abcd123", 
        		// some sms response id or message id
        	"email_response":"1234567890abc123", 
        		// some email response
        	"phone_call_response":"1234567890abc123",
        		// send the primary person an automated phone call that does something
        "autoresponse": {
            "enabled": true // this will enable all responses
         }
       }
    }
}
```

* Not all ids would be the same, could be some variation here.

This is different from a `message` resource as this is not a broadcast and only interacts with those who are signing up.

This is my basic idea so I'm open to improvments to this spec and if there are other autoresponse response types I think we could add them.

**Comment by j-ro** [comment]
This looks nice. I'd say to fit this into what we already have the trigger block would look like this:

```
"triggers": {
        	"autoresponse": {
                     "id: "123456789abcd123", 
                     "enabled": true
                 },
                 "sms_response": {
                     "id: "123456789abcd123", 
                     "enabled": true
                 }
       }
```

basically, the "autoresponse" hash is already defined in the spec as being an email response, so we'd be adding other options, plus the ID field within each hash I think?

**Comment by j-ro** [comment]
with multiple ids:

```
"triggers": {
        	"autoresponse": {
                     "identifiers: [
                          "action_network:123456789abcd123", 
                          "blue_state_digital:sduioerwsfsdsf"
                     ],
                     "enabled": true
                 },
                 "sms_response": {
                     "identifiers: [
                          "revmsg:123456789abcd123", 
                          "call_hub:sduioerwsfsdsf"
                     ],
                     "enabled": true
                 }
       }
```

**Comment by joshco** [comment]
@robertsonsamuel  Is there any update or ETA on this?

**Comment by robertsonsamuel** [comment]
Working on getting a pull request this week for the signup helper. I've been wearing many hats recently and traveling back and fourth between the US and Japan so things got a little out of control. I'll have something tomorrow for us and this spec!

**Comment by sonyabea** [comment]
closed by committee on 9/19/2018
