### ISSUE TITLE
TypeScript Definitions

### ISSUE THREAD

**Issue by natemoo-re** [opensupporter/osdi-docs#328]
Hello there!

I am currently in the process of generating TypeScript definitions for this spec, and I’d like to know if there’s interest in integrating the definitions directly with this repo or possibly a separate repo under opensupporter.

I’m happy to make a PR but figured opening an issue first was appropriate. 

This may be a possible solution to #283, as TypeScript has wide community support and there is a rich ecosystem of tools for converting TypeScript definitions to other formats such as Swagger.

**Comment by imjared** [comment]
hey @natemoo-re not sure how far along you are on this but I wanted to share with you that I've got a start here: https://github.com/imjared/osdi-types

I should note that I'm a bit of a beginner to TS so this might not be the best way to handle. I was mostly just trying to get baseline type definitions  for data models in an app I'm working on. Our app relies most heavily on the OSDI naming conventions and less so the API functionality.

If you have tips, think this is useful, or think my pass at it is complete 🗑, I'm curious to hear your thoughts!

**Comment by natemoo-re** [comment]
Hey @imjared, sorry for the delay!

You can take a look at my types at [civix-team/osdi-types](https://github.com/civix-team/osdi-types). Yours look pretty great, too! It would be great to collaborate on something that can benefit the whole community.

**Comment by joshco** [comment]
We can also discuss this tomorrow if you can make it

**Comment by joshco** [comment]
@natemoo-re can you email me at info@opensupporter.org ? we have a meeting tomorrow.

**Comment by joshco** [comment]
@natemoo-re If there's no further activity on this, the issue will be closed. 
If you are interested in providing technical feedback and wish to do so privately, in the closet, you can contact me at the OSDI Closet Hotline (516) 701 1900. You feedback will be related anonymously and your identity will only be known by me.
