### ISSUE TITLE
OSDI sandbox setup not working

### ISSUE THREAD

**Issue by Hull4Progress** [opensupporter/osdi-docs#336]
I am attempting to follow the instructions in the May 3, 2019, blog entry "OSDI 101: Zero to Person Signup Helper" at the URL http://opensupporter.org/category/blog/.  I have created a new slug | email address | name  << RickHullForNew | YOU flexbpm@hullrc.com | New Participant >>.  But when I click on "Visit" then I get an error message "We're sorry, but something went wrong.  // If you are the application owner check the logs for more information."

How can I make progress on this tutorial?

Thanks

**Comment by joshco** [comment]
I'll look at it, and get back to you.  thanks

**Comment by joshco** [comment]
Can you try creating a new one but using all lowercase letters?

**Comment by Hull4Progress** [comment]
Josh - thanks - everything is working, now that I used all lowercase letters.
